---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capi-kustomization
  namespace: flux-system
spec:
  interval: 1m0s
  path: .
  prune: true
  sourceRef:
    kind: GitRepository
    name: capi
  targetNamespace: default
