---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: capi
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/Anshika-Sharma-as/infra-capd.git
